### ISSUE TITLE
Peer review checklist

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-kubernetes-caching-hazelcast-spring#2]
Peer Review: review to be done by a peer member.

- [ ] Check that the guide has working instruction and sample code
- [ ] Check the quality of code according to the best coding practices
- [ ] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [ ] Check the consistency of guide with template and other guides
- [ ] Examples with the right outcomes are provided
- [ ] Example with the wrong outcomes, if any, are provided
- [ ] Check that all licensing statements are properly stated in all files
- [ ] Check that the `pom.xml`, `server.xml`, etc files are clean
- [ ] Check that the directories are properly structured
- [ ] Test the guide on 3 platforms: Mac, Win, Linux
- [ ] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [ ] If any URL visits, try `curl` command where applicable 
- [ ] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable
- [ ] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [ ] Check the `attribution` statement is accurate for the guide

**Comment by evelinec** [comment]
Pending on the content issues described in #12, before proceeding to work on the structure and styles for this guide.
