### ISSUE TITLE
Peer testing checklist

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-kubernetes-caching-hazelcast-spring#4]
Peer Testing: tests to be done by a peer member.

- [ ] Define test coverage and review with team (including guide contributor, if available)
- [ ] Define detail test cases 
- [ ] Consider corner cases targeting the specific guide
- [ ] Consider different platform tests, ie, Mac, Windows, Linux
- [ ] Consider corner cases UI tests
- [ ] Consider testing URL on all browsers, ie, FF, Chrome, Safari
- [ ] Consider testing the `curl` command for URL visits
- [ ] Consider Consider building with both Maven and Gradle build tools 
- [ ] Testing with different IDEs, ie, Atom, VS.code, Eclipse, IntelliJ, Microclimate
- [ ] Run Acrolink Checker on draft (above 70 score approximately)
- [ ] Consider SEO title and description for the guides 
- [ ] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [ ] Run `diff -r start/ finish/` and there's no differences
- [ ] Ensure that the automation tests are able to run with continuous daily builds
- [ ] Check the appearance of the guide on test site for the following items: 
- Table of contents 
- Headings
- Paragraphs
- code snippets
- outputs
- links
- hotspots
- [ ] Test the guide end-to-end with working instruction and sample code
- [ ] Perform all the defined test cases
